### ISSUE TITLE
DEVELOP 05: Domain Modeling

### ISSUE THREAD

**Issue by jerry914** [ITC-NTHU/LyricLab#6]
## Task

- [x] Update the description of your project
- [x] Create the domain objects you might need
- [x] Develop your Web Application
- [ ] Deploy your Web application to Heroku (AWS)

I couldn't find your Heroku Web App URL in the [Google Team Sheet](https://docs.google.com/spreadsheets/d/1in8nvVFMh99L_NCA-PDzP0xR529cWyqTXr9tJljar0M/edit?gid=983583323#gid=983583323). Please ensure your application is deployed online. Feel free to ask for assistance on Teams if you need any help.

## RuboCop/Code Smell Offenses

There are a large number of RuboCop offenses across different files. Please remember to check and modify them.

You're making great progress—keep pushing forward!

**Comment by soumyaray** [comment]
https://github.com/ITC-NTHU/LyricLab/blob/7e64eda04e99227fa5c4efa0e0c2b9b2db3b2e97/app/domain/aggregates/recommendations/recommendation.rb#L29

Hey folks, don't put methods in the domain entities that talk to the infrastructure – make a service object (this week) that calls the infrastructure directly. Updating the database is not business logic.

**Comment by soumyaray** [comment]
https://github.com/ITC-NTHU/LyricLab/blob/7e64eda04e99227fa5c4efa0e0c2b9b2db3b2e97/app/domain/aggregates/song/entities/vocabulary.rb#L27

Here again, don't ask domain entity to reach out to outside infrastructure (OpenAI)

**Comment by soumyaray** [comment]
Lastly, and this is a big one, none of your entities/values have any business logic yet. It seems that you are simply aggregating outside resources so far. Let me know if you need a session to discuss what/where your value-adding logic is!
